### ISSUE TITLE
Firebase is listed twice in the README

### ISSUE THREAD

**Issue by juiceboxh3ro** [realmayus/realmayus#1]
I'm definitely not abusing the green squares by raising this issue and then submitting a pull request, but you have Firebase listed twice in your readme. I think you should remove one, or refer to the database one as Firestore.

**Comment by realmayus** [comment]
Thank you *so* much. 
![](https://tenor.com/view/the-office-bow-michael-scott-steve-carell-office-gif-12985913.gif)
